### ISSUE TITLE
togglePine hotkey not being unregistered

### ISSUE THREAD

**Issue by realLevTheDev** [JLevy18/pine#1]
When attempting to change the togglePine hotkey, the previous key is not being unregistered resulting in both the old key and the new key being a toggle button.

**Comment by JLevy18** [comment]
This issue was related to the unregisterHotkeys() function in main.ts not being called when the reset button is clicked from the front end. unregisterHotkeys() is only called when stop-record-hotkey event is fired. This event does not get fired when the reset button gets clicked. 

To resolve this we unregister and register directly in the put-settings event now. There is code duplication here because unregisterHotkeys will still be called for the normal use case. For now, I am okay with this solution.

**Comment by realLevTheDev** [comment]
This issue was related to the unregisterHotkeys() function in main.ts not being called when the reset button is clicked from the front end. unregisterHotkeys() is only called when stop-record-hotkey event is fired. This event does not get fired when the reset button gets clicked.

To resolve this we unregister and register directly in the put-settings event now. There is code duplication here because unregisterHotkeys will still be called for the normal use case. For now, I am okay with this solution.
